"""simulation runs and ticket pool

Revision ID: ea4c6e542534
Revises: 5afcdf657f1a
Create Date: 2026-09-30 19:34:50.250299

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy  # noqa: F401  (GUID type used by auth tables)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ea4c6e542534"
down_revision: str | Sequence[str] | None = "5afcdf657f1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("pool_run_id", sa.Uuid(), nullable=True),
        sa.Column("scenario", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("planner", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("weeks", sa.Integer(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_week", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("weekly_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pool_run_id"],
            ["simulation_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_run_household_id"), "simulation_run", ["household_id"], unique=False
    )
    op.create_table(
        "sim_ticket",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("simulation_run_id", sa.Uuid(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("submitter", sa.String(length=100), nullable=False),
        sa.Column("style", sa.String(length=20), nullable=False),
        sa.Column(
            "true_category",
            sa.Enum(
                "chores",
                "groceries",
                "kids",
                "home_maintenance",
                "finance",
                "social",
                "other",
                name="true_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "true_effort",
            sa.Enum(
                "S",
                "M",
                "L",
                name="true_effort",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "text_effort",
            sa.Enum(
                "S",
                "M",
                "L",
                name="text_effort",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "gemini_category",
            sa.Enum(
                "chores",
                "groceries",
                "kids",
                "home_maintenance",
                "finance",
                "social",
                "other",
                name="gemini_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "gemini_effort",
            sa.Enum(
                "S",
                "M",
                "L",
                name="gemini_effort",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["simulation_run_id"], ["simulation_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sim_ticket_run_week", "sim_ticket", ["simulation_run_id", "week"], unique=False
    )
    op.add_column("topic", sa.Column("sim_ticket_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_topic_sim_ticket_id"), "topic", ["sim_ticket_id"], unique=False)
    op.create_foreign_key(
        None, "topic", "sim_ticket", ["sim_ticket_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "topic", type_="foreignkey")
    op.drop_index(op.f("ix_topic_sim_ticket_id"), table_name="topic")
    op.drop_column("topic", "sim_ticket_id")
    op.drop_index("ix_sim_ticket_run_week", table_name="sim_ticket")
    op.drop_table("sim_ticket")
    op.drop_index(op.f("ix_simulation_run_household_id"), table_name="simulation_run")
    op.drop_table("simulation_run")
    # ### end Alembic commands ###
