"""topic edit and soft delete

Revision ID: 5afcdf657f1a
Revises: d956285ec397
Create Date: 2026-09-30 19:23:53.986082

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy  # noqa: F401  (GUID type used by auth tables)
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5afcdf657f1a"
down_revision: str | Sequence[str] | None = "d956285ec397"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topic", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("topic", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "deleted_at")
    op.drop_column("topic", "updated_at")
    # ### end Alembic commands ###
