"""membership is_child and model artifacts

Revision ID: 5788a804dbd8
Revises: da4233b145e4
Create Date: 2026-09-29 13:11:53.680558

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy  # noqa: F401  (GUID type used by auth tables)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5788a804dbd8"
down_revision: str | Sequence[str] | None = "da4233b145e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_artifact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "invite",
        sa.Column("is_child", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "membership",
        sa.Column("is_child", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # Backfill: simulated members already know their role from the family profile.
    op.execute("UPDATE membership SET is_child = true WHERE profile ->> 'role' = 'kid'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("membership", "is_child")
    op.drop_column("invite", "is_child")
    op.drop_table("model_artifact")
    # ### end Alembic commands ###
