"""demo families and generation runs

Revision ID: da4233b145e4
Revises: 3cea6787388c
Create Date: 2026-09-29 11:14:59.048666

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy  # noqa: F401  (GUID type used by auth tables)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da4233b145e4"
down_revision: str | Sequence[str] | None = "3cea6787388c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_profile",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preset_key", sa.String(length=50), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("household_id"),
    )
    op.create_table(
        "generation_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("requested", sa.Integer(), nullable=False),
        sa.Column("produced", sa.Integer(), nullable=False),
        sa.Column("rejected_invalid", sa.Integer(), nullable=False),
        sa.Column("rejected_duplicate", sa.Integer(), nullable=False),
        sa.Column("category_mismatches", sa.Integer(), nullable=False),
        sa.Column("models_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_run_household_id"), "generation_run", ["household_id"], unique=False
    )
    op.add_column("topic", sa.Column("generation_run_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_topic_generation_run_id"), "topic", ["generation_run_id"], unique=False
    )
    op.create_foreign_key(
        None, "topic", "generation_run", ["generation_run_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "topic", type_="foreignkey")
    op.drop_index(op.f("ix_topic_generation_run_id"), table_name="topic")
    op.drop_column("topic", "generation_run_id")
    op.drop_index(op.f("ix_generation_run_household_id"), table_name="generation_run")
    op.drop_table("generation_run")
    op.drop_table("family_profile")
    # ### end Alembic commands ###
