"""simulation model overrides

Revision ID: 439f084f38d2
Revises: ea4c6e542534
Create Date: 2026-09-30 22:21:39.569880

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy  # noqa: F401  (GUID type used by auth tables)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "439f084f38d2"
down_revision: str | Sequence[str] | None = "ea4c6e542534"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_run",
        sa.Column("model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_run", "model_versions")
    # ### end Alembic commands ###
