"""sprints

Revision ID: d956285ec397
Revises: 5788a804dbd8
Create Date: 2026-09-29 15:03:16.958222

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy  # noqa: F401  (GUID type used by auth tables)
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d956285ec397"
down_revision: str | Sequence[str] | None = "5788a804dbd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sprint",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "active",
                "completed",
                name="sprintstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sprint_household_status", "sprint", ["household_id", "status"], unique=False
    )
    op.create_table(
        "sprint_review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sprint_id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("reviewed_by", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sprint_id"], ["sprint.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sprint_id"),
    )
    op.create_index(
        op.f("ix_sprint_review_household_id"), "sprint_review", ["household_id"], unique=False
    )
    op.create_table(
        "sprint_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sprint_id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "todo",
                "in_progress",
                "done",
                name="itemstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column(
            "effort_actual",
            sa.Enum(
                "S", "M", "L", name="effort", native_enum=False, create_constraint=True, length=32
            ),
            nullable=True,
        ),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
        sa.ForeignKeyConstraint(["assignee_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["household_id"], ["household.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sprint_id"], ["sprint.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sprint_id", "topic_id", name="uq_sprint_item_topic"),
    )
    op.create_index(
        op.f("ix_sprint_item_household_id"), "sprint_item", ["household_id"], unique=False
    )
    op.create_index(op.f("ix_sprint_item_sprint_id"), "sprint_item", ["sprint_id"], unique=False)
    op.create_index(op.f("ix_sprint_item_topic_id"), "sprint_item", ["topic_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sprint_item_topic_id"), table_name="sprint_item")
    op.drop_index(op.f("ix_sprint_item_sprint_id"), table_name="sprint_item")
    op.drop_index(op.f("ix_sprint_item_household_id"), table_name="sprint_item")
    op.drop_table("sprint_item")
    op.drop_index(op.f("ix_sprint_review_household_id"), table_name="sprint_review")
    op.drop_table("sprint_review")
    op.drop_index("ix_sprint_household_status", table_name="sprint")
    op.drop_table("sprint")
    # ### end Alembic commands ###
